# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - 0.6
  - nightly
  
matrix:
  allow_failures:
    - julia: nightly
    
notifications:
  email: false
  
env:
  - DOCUMENTER_DEBUG=true
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("Checkers",coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Checkers","docs")); include("make.jl")'
  #- julia -e 'cd(Pkg.dir("Checkers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Checkers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
