site_name:           Checkers.jl
repo_url:            https://github.com/pkalikman/Checkers.jl
site_description:    QuickCheck-like Automated Testing Macros for Julia
site_author:         pkalikman

theme: readthedocs

extra:
  palette:
    primary: 'deep purple'
    accent: 'cyan'

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
  - Home: 'index.md'
  - Macros:
      - Test-forall: 'macros/test-forall.md'
      - Test-formany: 'macros/test-formany.md'
      - Test-exists: 'macros/test-exists.md'
